spring:
  jpa:
    hibernate:
      ddl-auto: none

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        # Tắt tính năng tự động nhét lại tin nhắn lỗi vào Queue (Cắt đứt vòng lặp vô tận)
        default-requeue-rejected: false
        retry:
          # Bật cơ chế thử lại của Spring
          enabled: true
          # Chỉ cho phép gọi tối đa 3 lần
          max-attempts: 3
          # Khoảng thời gian chờ giữa các lần thử (2 giây)
          initial-interval: 2s

app:
  cookie:
    secure: false

server:
  port: 8080
