application:
  service:
    impl:
      deepseek:
        api-key: ${DEEP_SEEK_API_KEY}
      gemini:
        api-key: ${GEMINI_API_KEY}
      secret-key: ${SECRET_KEY}
      expiration: 600000
      amount: 10
      timeLimit: 604800
      max-attemps: 5
      time-out-first: 600
      time-out-second: 86400
      subject-verify: "Kích hoạt tài khoản JobList của bạn"
      email-verify: "Xin chào bạn,Cảm ơn bạn đã đăng ký tài khoản tại JobList. Để hoàn tất quá trình đăng ký, vui lòng nhấn vào liên kết dưới đây để kích hoạt tài khoản: %s . Nếu bạn không thực hiện yêu cầu này, vui lòng bỏ qua email này. Trân trọng, JobList Team."
      subject-oauth2: "Xác thực tài khoản JobList & tạo mật khẩu mới"
      email-oauth2: |
        Chào %s,

        Bạn đang đăng nhập vào JobList lần đầu bằng tài khoản mạng xã hội. Vì vậy, hệ thống chưa có mật khẩu.
        Để bảo vệ tài khoản của bạn, vui lòng xác thực quyền sở hữu email
        và tạo mật khẩu mới qua liên kết sau:

        %s

        Lưu ý:
        • Liên kết này có hiệu lực trong 1 giờ.
        • Nếu bạn không yêu cầu việc này, bạn có thể bỏ qua email này.
        • Mật khẩu nên bao gồm ít nhất 8 ký tự, gồm chữ hoa, chữ thường và số để bảo mật tốt hơn.

        Nếu bạn gặp sự cố, xin vui lòng liên hệ với bộ phận hỗ trợ tại support@joblist.vn hoặc phản hồi email này.

        Cảm ơn bạn đã sử dụng JobList,
        Chúc bạn một ngày tốt lành
        - JobList Team
  config:
    redis:
      host-name: 127.0.0.1
      username:
      port: 6379
      password: ${REDIS_PASSWORD}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        # Tắt tính năng tự động nhét lại tin nhắn lỗi vào Queue (Cắt đứt vòng lặp vô tận)
        default-requeue-rejected: false
        retry:
          # Bật cơ chế thử lại của Spring
          enabled: true
          # Chỉ cho phép gọi tối đa 3 lần
          max-attempts: 3
          # Khoảng thời gian chờ giữa các lần thử (2 giây)
          initial-interval: 2s

  mail:
    host: smtp.gmail.com
    port: 465
    default-encoding: UTF-8
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
      resource-server:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  ocr:
    api-key: ${OCR_API_KEY}
  ai:
    agent:
      base-url: https://votanthanh32004-job-portal-matching.hf.space

app:
  cookie:
    secure: false

server:
  port: 8080


cloudflare:
  r2:
    account-id: ${CLOUDFLARE_ACCOUNT_ID}
    access-key: ${CLOUDFLARE_ACCESS_KEY}
    secret-key: ${CLOUDFLARE_SECRET_KEY}
    bucket-name: job-portal-resume
    endpoint: https://${cloudflare.r2.account-id}.r2.cloudflarestorage.com
