spring:
  jpa:
    hibernate:
      ddl-auto: none

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT} # Mặc định là 5671 cho SSL
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_USER} # Thay đổi theo vhost của bạn
    ssl:
      enabled: true

app:
  cookie:
    secure: true

server:
  port: ${PORT:8080}