/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        'error-container': '#fb5151',
        'on-background': '#282b51',
        'surface-dim': '#cfd1ff',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#282b51',
        'surface-container-highest': '#d9daff',
        'primary-container': '#7b9cff',
        'on-error': '#ffefee',
        tertiary: '#8e3a8a',
        outline: '#71749e',
        'inverse-on-surface': '#9799c6',
        surface: '#f8f5ff',
        'on-tertiary-container': '#661466',
        'on-secondary-container': '#323aa2',
        'secondary-dim': '#3b43aa',
        'on-primary-fixed': '#000000',
        'on-primary-container': '#001e5a',
        secondary: '#4850b7',
        'on-primary': '#f1f2ff',
        'on-secondary': '#f3f1ff',
        'tertiary-container': '#fe9cf4',
        'surface-container-low': '#f1efff',
        'on-surface-variant': '#555881',
        'inverse-surface': '#06092f',
        'surface-variant': '#d9daff',
        'on-error-container': '#570008',
        background: '#f8f5ff',
        error: '#b31b25',
        'secondary-container': '#cbceff',
        'tertiary-fixed': '#fe9cf4',
        'on-tertiary-fixed': '#480049',
        'on-secondary-fixed': '#1c248e',
        'surface-bright': '#f8f5ff',
        'on-primary-fixed-variant': '#00266e',
        primary: '#0050d4',
        'surface-container-high': '#e0e0ff',
        'tertiary-fixed-dim': '#ef8fe5',
        'surface-tint': '#0050d4',
        'primary-dim': '#0046bb',
        'inverse-primary': '#618bff',
        'on-secondary-fixed-variant': '#3c45ab',
        'on-tertiary': '#ffeef8',
        'secondary-fixed-dim': '#bbbfff',
        'outline-variant': '#a7aad7',
        'on-tertiary-fixed-variant': '#711f6f',
        'error-dim': '#9f0519',
        'tertiary-dim': '#802d7d',
        'primary-fixed-dim': '#658eff',
        'surface-container': '#e7e6ff',
        'secondary-fixed': '#cbceff',
        'primary-fixed': '#7b9cff'
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {},
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'ambient': '0 8px 32px 0 rgba(0, 80, 212, 0.05)',
        'glass': '0 4px 24px 0 rgba(0, 80, 212, 0.08)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'), // Thêm dòng này vào đây
  ],
}