/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/features/admin/**/*.{html,ts}",
    "./src/app/features/recruiter/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        // --- Admin Colors ---
        'ad-error-container': '#fb5151',
        'ad-on-background': '#282b51',
        'ad-surface-dim': '#cfd1ff',
        'ad-surface-container-lowest': '#ffffff',
        'ad-on-surface': '#282b51',
        'ad-surface-container-highest': '#d9daff',
        'ad-primary-container': '#7b9cff',
        'ad-on-error': '#ffefee',
        'ad-tertiary': '#8e3a8a',
        'ad-outline': '#71749e',
        'ad-inverse-on-surface': '#9799c6',
        'ad-surface': '#f8f5ff',
        'ad-on-tertiary-container': '#661466',
        'ad-on-secondary-container': '#323aa2',
        'ad-secondary-dim': '#3b43aa',
        'ad-on-primary-fixed': '#000000',
        'ad-on-primary-container': '#001e5a',
        'ad-secondary': '#4850b7',
        'ad-on-primary': '#f1f2ff',
        'ad-on-secondary': '#f3f1ff',
        'ad-tertiary-container': '#fe9cf4',
        'ad-surface-container-low': '#f1efff',
        'ad-on-surface-variant': '#555881',
        'ad-inverse-surface': '#06092f',
        'ad-surface-variant': '#d9daff',
        'ad-on-error-container': '#570008',
        'ad-background': '#f8f5ff',
        'ad-error': '#b31b25',
        'ad-secondary-container': '#cbceff',
        'ad-tertiary-fixed': '#fe9cf4',
        'ad-on-tertiary-fixed': '#480049',
        'ad-on-secondary-fixed': '#1c248e',
        'ad-surface-bright': '#f8f5ff',
        'ad-on-primary-fixed-variant': '#00266e',
        'ad-primary': '#0050d4',
        'ad-surface-container-high': '#e0e0ff',
        'ad-tertiary-fixed-dim': '#ef8fe5',
        'ad-surface-tint': '#0050d4',
        'ad-primary-dim': '#0046bb',
        'ad-inverse-primary': '#618bff',
        'ad-on-secondary-fixed-variant': '#3c45ab',
        'ad-on-tertiary': '#ffeef8',
        'ad-secondary-fixed-dim': '#bbbfff',
        'ad-outline-variant': '#a7aad7',
        'ad-on-tertiary-fixed-variant': '#711f6f',
        'ad-error-dim': '#9f0519',
        'ad-tertiary-dim': '#802d7d',
        'ad-primary-fixed-dim': '#658eff',
        'ad-surface-container': '#e7e6ff',
        'ad-secondary-fixed': '#cbceff',
        'ad-primary-fixed': '#7b9cff',

        // --- Recruiter Colors ---
        "re-on-background": "#191c1e",
        "re-surface": "#f7f9fb",
        "re-surface-container-low": "#f2f4f6",
        "re-on-secondary-fixed-variant": "#004c6e",
        "re-secondary-fixed-dim": "#89ceff",
        "re-primary-fixed": "#dbe1ff",
        "re-on-surface-variant": "#434655",
        "re-on-primary-container": "#eeefff",
        "re-surface-container-highest": "#e0e3e5",
        "re-on-error": "#ffffff",
        "re-surface-tint": "#0053db",
        "re-primary-fixed-dim": "#b4c5ff",
        "re-error": "#ba1a1a",
        "re-on-secondary-fixed": "#001e2f",
        "re-surface-container": "#eceef0",
        "re-tertiary-container": "#943fe2",
        "re-secondary-fixed": "#c9e6ff",
        "re-tertiary-fixed": "#f0dbff",
        "re-on-secondary": "#ffffff",
        "re-secondary-container": "#39b8fd",
        "re-tertiary-fixed-dim": "#ddb7ff",
        "re-error-container": "#ffdad6",
        "re-on-tertiary-fixed": "#2c0051",
        "re-inverse-surface": "#2d3133",
        "re-on-primary": "#ffffff",
        "re-background": "#f7f9fb",
        "re-on-surface": "#191c1e",
        "re-tertiary": "#7a1bc8",
        "re-surface-variant": "#e0e3e5",
        "re-on-secondary-container": "#004666",
        "re-on-primary-fixed-variant": "#003ea8",
        "re-primary-container": "#2563eb",
        "re-surface-container-high": "#e6e8ea",
        "re-surface-container-lowest": "#ffffff",
        "re-on-tertiary": "#ffffff",
        "re-inverse-primary": "#b4c5ff",
        "re-on-primary-fixed": "#00174b",
        "re-secondary": "#006591",
        "re-inverse-on-surface": "#eff1f3",
        "re-outline": "#737686",
        "re-on-tertiary-fixed-variant": "#6900b3",
        "re-on-error-container": "#93000a",
        "re-outline-variant": "#c3c6d7",
        "re-surface-bright": "#f7f9fb",
        "re-on-tertiary-container": "#faecff",
        "re-primary": "#004ac6",
        "re-surface-dim": "#d8dadc"
      },
      borderRadius: {
        // Admin
        'ad-DEFAULT': "0.125rem",
        'ad-lg': "0.25rem",
        'ad-xl': "0.5rem",
        'ad-full': "0.75rem",
        // Recruiter
        "re-DEFAULT": "0.25rem",
        "re-lg": "0.5rem",
        "re-xl": "0.75rem",
        "re-full": "9999px"
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        // Admin specific
        manrope: ['Manrope', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'ad-ambient': '0 8px 32px 0 rgba(0, 80, 212, 0.05)',
        'ad-glass': '0 4px 24px 0 rgba(0, 80, 212, 0.08)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
